config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root 'home#index'

  resources :file_histories, only: %i[create]
  resources :parlamentarians, only: [] do
    resources :expenses, only: %i[index show]
  end

  mount Sidekiq::Web => '/sidekiq'

  get '*path' => redirect('/')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/expense.rb
class Expense < ApplicationRecord
  # Relationships
  belongs_to :parlamentarian, required: true
  # Validations
  validates :id_document, presence: true
  validates :date_issue, presence: true
  validates :value, presence: true

  def self.top(limit = 5)
    order(value: :desc).limit(limit)
  end

  def self.chart_top_providers(limit = 5)
    group(:provider)
      .sum(:value)
      .sort_by { |k, v| -v }.first(limit).to_h
  end

  def self.chart_by_month
    group_by_month_of_year(:date_issue, time_zone: false)
      .sum(:value)
      .map{ |k, v| [I18n.t('date.month_names')[k], v] }
  end
end

app/models/file_history.rb
# frozen_string_literal: true

class FileHistory < ApplicationRecord
  # Enums
  enum status: {
    pending: 0,
    success: 1,
    failure: 2
  }
  # ActiveStorage
  has_one_attached :file
  validates :file, attached: true, content_type: { in: 'text/csv', message: 'não é um .CSV' }
  # Validations
  validates :status, presence: true
  validates :description, presence: true
  validates :message, presence: true, if: :failure?
end

app/models/parlamentarian.rb
class Parlamentarian < ApplicationRecord
  # Relationships
  has_many :expenses, dependent: :destroy
  # Validations
  validates :id_register, presence: true, uniqueness: { case_sensitive: false }
  validates :uf, presence: true
  validates :num_legislature, presence: true
  validates :name, presence: true
  validates :cod_legislature, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Exceptions
end

app/controllers/concerns/exceptions.rb
module Exceptions
  extend ActiveSupport::Concern

  included do
    rescue_from ActionController::InvalidAuthenticityToken, with: :invalid_token
    rescue_from ActiveRecord::RecordNotFound, with: :not_found
    rescue_from PG::RaiseException, with: :pg_raise
    rescue_from RuntimeError, with: :runtime_error

    def invalid_token
      render_error('Invalid Authenticity Token.')
    end

    def not_found
      render_error('Registro não encontrado.')
    end

    def pg_raise(error)
      render_error(error)
    end

    def runtime_error(error)
      render_error(error)
    end
    
    def render_error(message)
      redirect_back fallback_location: root_path, flash: { error: message }
    end
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_parlamentarian
  before_action :set_expense, only: %i[show]

  def index
    @top7_expenses = @parlamentarian.expenses.top(7)
    @month_chart = @parlamentarian.expenses.chart_by_month
    @provider_chart = @parlamentarian.expenses.chart_top_providers(5)

    @ransack = @parlamentarian.expenses.ransack(params[:q])
    @ransack.sorts = 'date_issue ASC' if @ransack.sorts.empty?
    @expenses = @ransack.result.page(params[:page])
  end

  def show; end

  private

  def set_parlamentarian
    @parlamentarian = Parlamentarian.find(params[:parlamentarian_id])
  end

  def set_expense
    @expense = @parlamentarian.expenses.find(params[:id])
  end
end

app/controllers/file_histories_controller.rb
# frozen_string_literal: true

# Controller to store the history of files sent from csv
class FileHistoriesController < ApplicationController

  def create
    @file_history = FileHistory.new(file_history_params)

    if @file_history.save
      ProcessPendingFileHistoryJob.perform_later(@file_history.id)
      redirect_to root_path, notice: t('.success_return')
    else
      redirect_back fallback_location: root_path,
                    flash: { error: @file_history.errors.full_messages.join('<br/>') }
    end
  end

  private

  def file_history_params
    params.require(:file_history).permit(:file, :description)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @file_history = FileHistory.new

    @ransack = Parlamentarian.ransack(params[:q])
    @ransack.sorts = 'total DESC' if @ransack.sorts.empty?
    @parlamentarians = @ransack.result.page(params[:page])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_message(obj = nil, msg = [])
    titulo = css = nil
    %i[notice alert error information].each do |flash_type|
      flash[flash_type] = params[flash_type] if params[flash_type].present?
      next unless flash[flash_type].present?

      titulo, css = flash_message_style(flash_type)
      msg = flash[flash_type].split('<br/>')
      flash[flash_type] = nil
    end
    if obj && !obj.errors.full_messages.blank?
      titulo, css = flash_message_style(:error)
      obj.errors.full_messages.uniq.each do |erro|
        msg << erro.to_s.gsub('base', '')
      end
    end
    render_haml <<-HAML, msg: msg, titulo: titulo, css: css
      - msg.each do |texto|
        .div-flash
          %div{class: css}
            %span
              = titulo
              = texto
    HAML
  end

  def flash_message_style(flash_type)
    flash_data = { success:      ['Informação: ', 'alert alert-success'],
                   alert:        ['Atenção: ',    'alert alert-warning'],
                   warning:      ['Atenção: ',    'alert alert-warning'],
                   error:        ['Erros: ',      'alert alert-danger'],
                   information:  ['Nota: ',       'alert alert-info'],
                   notice:       ['Informação: ', 'alert alert-success'] }
    if flash_data[flash_type].present?
      flash_data[flash_type]
    else
      ['Nota: ', 'alert alert-default']
    end
  end

  def label_class(size)
    "col-sm-#{size} col-form-label text-right"
  end

  def btn_class(options = [:default], rounded: true)
    btn  = 'btn mr-0'
    btn += ' rounded-pill' if rounded
    options = [options] unless options.is_a?(Array)
    btn += options.map { |option| " btn-#{option.to_s}" }.join('')
    btn
  end

  def render_haml(haml, locals = {})
    Haml::Engine.new(haml.strip_heredoc, format: :html5).render(self, locals)
  end
end

app/helpers/expenses_helper.rb
module ExpensesHelper

  def details_expense(expense)
    "#{l(expense.date_issue)} - #{expense.provider} - #{number_to_currency(expense.value)}"
  end
end

app/helpers/parlamentarians_helper.rb
module ParlamentariansHelper

  def image_parlamentarian_url(id)
    "http://www.camara.leg.br/internet/deputado/bandep/#{id}.jpg"
  end
end

app/views/expenses/_list.html.haml
- model_class = Expense
.row
  .col.card.shadow.overflow-inherit
    .d-sm-flex.align-items-center.justify-content-between.pb-3.pt-3
      .h4.title-gray= t('.title')
    = search_form_for @ransack, url: parlamentarian_expenses_path(@parlamentarian), class: 'form-inline' do |f|
      .form-group.mb-2
        = f.label :name, "Pesquisar pelo Fornecedor"
      .form-group.mx-sm-3.mb-2
        = f.text_field :provider_cont, class: 'form-control'
      = f.submit t('helpers.submit.search'), class: 'btn btn-primary mb-2'
      = link_to t('helpers.submit.clear'), nil, class: 'btn btn-link mb-2'
    .table-responsive
      %table.table.table-hover.table-borderless.text-center
        %thead.thead-light
          %tr
            %th{title: model_class.human_attribute_name(:date_issue)}
              = sort_link(@ransack, :date_issue, model_class.human_attribute_name(:date_issue))
            %th{title: model_class.human_attribute_name(:provider)}
              = sort_link(@ransack, :provider, model_class.human_attribute_name(:provider))
            %th{title: model_class.human_attribute_name(:value)}
              = sort_link(@ransack, :value, model_class.human_attribute_name(:value))
            %th{title: model_class.human_attribute_name(:url_document)}
              = model_class.human_attribute_name(:url_document)
        %tbody
          - @expenses.each do |expense|
            %tr
              %td=l expense.date_issue
              %td= expense.provider
              %td= number_to_currency(expense.value)
              %td
                = link_to expense.url_document, target: '_blank' do
                  %i.fas.fa-file
    .d-flex.justify-content-between
      #left.bd-highlight
      %center.bd-highlight.page
        = paginate @expenses, remote: true
        = page_entries_info @expenses
      #right.bd-highlight

app/views/expenses/index.html.haml
.row
  .col-md-3.pl-0.pb-3
    .card.text-center.shadow.overflow-inherit
      %img.card-img-top{:alt => "Card image cap", src: image_parlamentarian_url(@parlamentarian.id_register)}/
      .card-body
        %h5.card-title.mb-0= @parlamentarian.name
      %ul.list-group.list-group-flush
        %li.list-group-item= t('.expenses_total', total: number_to_currency(@parlamentarian.total))
  .col-md-9.pr-0
    .card.shadow.overflow-inherit.p-3
      .d-sm-flex.align-items-center.justify-content-between.pb-3.pt-3
        .h4.title-gray= t('.top5_title')
      .list-group
        - @top7_expenses.each do |expense|
          .list-group-item.list-group-item-action
            = details_expense(expense)
.row
  .col-md-6.pl-0.pb-3
    .card.shadow.overflow-inherit.p-3
      .d-sm-flex.align-items-center.justify-content-between.pb-3.pt-3
        .h4.title-gray= t('.month_expense_title')
      = column_chart @month_chart, prefix: 'R$', thousands: ".", decimal: ','
  .col-md-6.pr-0
    .card.shadow.overflow-inherit.p-3
      .d-sm-flex.align-items-center.justify-content-between.pb-3.pt-3
        .h4.title-gray= t('.provider_title')
      = pie_chart @provider_chart, prefix: 'R$', thousands: ".", decimal: ','
#list
  = render partial: 'list'

app/views/expenses/index.js.haml
$('#list').empty();
$('#list').append('#{escape_javascript(render partial: 'list')}');

app/views/home/index.html.haml
- model_class = FileHistory
.row.mb-3
  .col.card.shadow.overflow-inherit
    .d-sm-flex.align-items-center.justify-content-between.pb-3.pt-3
      .h4.title-gray= t('.send_csv_file')
    = form_with model: @file_history, url: file_histories_path(@file_history), method: :post do |f|
      .card-body
        .form-group.row
          = f.label :description, model_class.human_attribute_name(:description),
                                  class: label_class(3)
          .col-md-9
            = f.text_field :description, required: true, class: 'form-control'
        .form-group.row
          = f.label :file, model_class.human_attribute_name(:file), class: label_class(3)
          .col-9
            = f.file_field :file, accept: '.csv', required: true, direct_upload: true, multiple: false
        .form-group.float-right
          = f.submit t('.send', default: t('helpers.submit.send')), class: btn_class(:primary)
#list
  = render partial: 'parlamentarians/list'

app/views/home/index.js.haml
$('#list').empty();
$('#list').append('#{escape_javascript(render partial: 'parlamentarians/list')}');

app/views/layouts/_header.html.haml
.row
  .col-auto.mr-auto
    = link_to root_path do
      %i.fas.fa-home.fa-3x
  .col
    %h2.text-center.pb-3{style: 'color: #007bff'}= t('.title')
.row
.row
  .col.p-0
    = flash_message
.row.mb-3
  .col.card.shadow.overflow-inherit.p-3
    %p.mb-0= t('.description')

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title DesafioBackend
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    / Custom fonts for this template
    -#%link{:href => "vendor/fontawesome-free/css/all.min.css", :rel => "stylesheet", :type => "text/css"}/
    -#%link{:href => "https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i", :rel => "stylesheet"}/
  %body#page-top
    #wrapper
      #content-wrapper.d-flex.flex-column
        #content{style: 'min-height: 900px'}
          .container.pt-4
            = render '/layouts/header'
            = yield
    %footer.custom-footer
      %p
        © 2020 - Daniel Fernandes Vieira

app/views/parlamentarians/_list.html.haml
- model_class = Parlamentarian
.row
  .col.card.shadow.overflow-inherit
    .d-sm-flex.align-items-center.justify-content-between.pb-3.pt-3
      .h4.title-gray= t('.title')
    = search_form_for @ransack, url: root_path, class: 'form-inline' do |f|
      .form-group.mb-2
        = f.label :name, "Pesquisar pelo Nome ou Partido"
      .form-group.mx-sm-3.mb-2
        = f.text_field :name_or_political_party_cont, class: 'form-control'
      = f.submit t('helpers.submit.search'), class: 'btn btn-primary mb-2'
      = link_to t('helpers.submit.clear'), root_path, class: 'btn btn-link mb-2'
    .table-responsive
      %table.table.table-hover.table-borderless.text-center
        %thead.thead-light
          %tr
            %th{title: model_class.human_attribute_name(:id_register_detail)}
              = sort_link(@ransack, :id_register, model_class.human_attribute_name(:id_register))
            %th{title: model_class.human_attribute_name(:name_detail)}
              = sort_link(@ransack, :name, model_class.human_attribute_name(:name))
            %th{title: model_class.human_attribute_name(:political_party_detail)}
              = sort_link(@ransack, :political_party, model_class.human_attribute_name(:political_party))
            %th= sort_link(@ransack, :total, t('.total'))
            %th= t('helpers.list.actions')
        %tbody
          - @parlamentarians.each do |parlamentarian|
            %tr
              %td= parlamentarian.id_register
              %td= parlamentarian.name
              %td= parlamentarian.political_party
              %td= number_to_currency(parlamentarian.total)
              %td
                = link_to parlamentarian_expenses_path(parlamentarian) do
                  %i.fas.fa-search
    .d-flex.justify-content-between
      #left.bd-highlight
      %center.bd-highlight.page
        = paginate @parlamentarians, remote: true
        = page_entries_info @parlamentarians
      #right.bd-highlight